[package]
name = "bi_fs_rs"
version = "1.0.0"
edition = "2024"
authors = ["Perondas <thomas@perondas.dev>"]
license = "GPL-3.0"
description = "A Rust library for working with Arma 3 related file formats, such as PBO and BISIGN files."
repository = "https://github.com/Perondas/bi_fs_rs"
categories = ["file-formats", "utilities"]
keywords = ["arma3", "pbo", "bisign", "file-formats"]
readme = "README.md"

[dependencies]
anyhow = "1.0.98"
rsa = "0.9.10"
sha1 = "0.10.6"
binrw = "0.15.0"
nutype = "0.6.1"
rand = "0.8.5"
